# TODO:: Use secrets
spring.datasource.url=jdbc:postgresql://localhost:5432/electricity
spring.datasource.username=academy
# TODO:: Use secrets
spring.datasource.password=academy
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

logging.level.org.springframework.web=DEBUG

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.csrf.enabled=false