# NB. We have bunch of default values here for local development.
# We should do application-dev.properties instead for default values.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/electricity}
spring.datasource.username=${DB_USERNAME:academy}
spring.datasource.password=${DB_PASSWORD:academy}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Limit the number of instances to not exhaust the SupaBase free tier connection limit.
spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:5}

# NB. Cloud Run injects PORT and expects the container to listen on it.
server.port=${PORT:8080}

logging.level.org.springframework.web=${WEB_LOG_LEVEL:INFO}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.csrf.enabled=false
